### ISSUE TITLE
Add economics to Manager

### ISSUE THREAD

**Issue by smartcontracts** [chugsplash/chugsplash#30]
Whenever an action is executed via the ChugSplashManager contract, the ChugSplashManager should compute a payment according to the [Executor Payment Strategy](https://github.com/smartcontracts/chugsplash/blob/develop/specs/executor-economics.md#executor-payment-strategies) contract configured for the project. The Executor Payment Strategy contract must NOT be allowed to change once a deployment is approved.

**Comment by sam-goldman** [comment]
Closed by #64
