### ISSUE TITLE
Create simple economics module

### ISSUE THREAD

**Issue by smartcontracts** [chugsplash/chugsplash#32]
Once we have added Executor Payment Strategies to the ChugSplashManager, we should introduce a simple Executor Payment Strategy for the demo. I recommend that we do the simple [flat fee strategy](https://github.com/smartcontracts/chugsplash/blob/develop/specs/executor-economics.md#eps-1-flat-fee) described in the specs.

**Comment by sam-goldman** [comment]
Closed by #64
