### ISSUE TITLE
Conflict between @chugsplash/plugins and solidity-coverage

### ISSUE THREAD

**Issue by marc-aurele-besner** [chugsplash/chugsplash#523]
When @chugsplash/plugins is imported in the hardhat config file, and we try to run a coverage test using solidity-coverage
the reports are empty.

If I remove @chugsplash/plugins to run the coverage tests work fine

A temporary workaround can be to have a separate hardhat config file to run coverage with

**Comment by sam-goldman** [comment]
Hey @marc-aurele-besner, thanks for pointing this out. Sorry it took a while to get to this - we've been busy getting our codebase ready for an audit. We fixed this issue in the latest package versions, which we'll release after the audit (in roughly a month). You shouldn't have any issues integrating with solidity-coverage after that.
